services:
  app:
    image: ziwangga/getting-started-app:v3
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data: